# 1) бэкап
cp docker-compose.yml docker-compose.yml.bak.$(date +%s)

# 2) заменить SOCKS5 на наш HTTP-прокси S1
sed -i 's#socks5h://host.docker.internal:9090#http://51.158.76.113:9999#g' docker-compose.yml

# 3) добавить NO_PROXY (чтобы внутренние вызовы не шли через прокси)
# если строк уже нет — просто добавим под каждым environment: блока backend и worker
awk '
/^  backend:$/,/^  db:$/{
  if ($0 ~ /^    environment:/ && b==0) {print; print "      NO_PROXY: \"localhost,127.0.0.1,nginx,frontend,db,redis,engineering-hub-nginx,engineering-hub-frontend,engineering-hub-db,engineering-hub-redis\""; print "      no_proxy: \"localhost,127.0.0.1,nginx,frontend,db,redis,engineering-hub-nginx,engineering-hub-frontend,engineering-hub-db,engineering-hub-redis\""; b=1; next}
  print; next
}
/^  worker:$/,/^volumes:$/{
  if ($0 ~ /^    environment:/ && w==0) {print; print "      NO_PROXY: \"localhost,127.0.0.1,nginx,frontend,db,redis,engineering-hub-nginx,engineering-hub-frontend,engineering-hub-db,engineering-hub-redis\""; print "      no_proxy: \"localhost,127.0.0.1,nginx,frontend,db,redis,engineering-hub-nginx,engineering-hub-frontend,engineering-hub-db,engineering-hub-redis\""; w=1; next}
  print; next
}
{print}
' docker-compose.yml > docker-compose.tmp && mv docker-compose.tmp docker-compose.yml

# 4) перезапустить два сервиса
docker compose up -d backend worker 2>/dev/null || docker-compose up -d backend worker

# 5) показать последние строки логов
docker compose logs backend --tail=120 2>/dev/null || docker-compose logs backend --tail=120
docker compose logs worker  --tail=120 2>/dev/null || docker-compose logs worker  --tail=120
