version: '3.8'

services:
  nginx:
    container_name: engineering-hub-nginx
    build: ./nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend

  frontend:
    container_name: engineering-hub-frontend
    build: ./frontend
    restart: unless-stopped
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  backend:
    container_name: engineering-hub-backend
    build: ./backend
    restart: unless-stopped
    env_file: .env
    environment:
      # HTTP-прокси для исходящих запросов Google и др.
      HTTP_PROXY:  "http://51.158.76.113:9999"
      HTTPS_PROXY: "http://51.158.76.113:9999"
      http_proxy:  "http://51.158.76.113:9999"
      https_proxy: "http://51.158.76.113:9999"
      # Не проксировать внутренние сервисы/localhost
      NO_PROXY:  "localhost,127.0.0.1,nginx,frontend,db,redis,engineering-hub-nginx,engineering-hub-frontend,engineering-hub-db,engineering-hub-redis"
      no_proxy:  "localhost,127.0.0.1,nginx,frontend,db,redis,engineering-hub-nginx,engineering-hub-frontend,engineering-hub-db,engineering-hub-redis"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./backend:/app
      - ./config.json:/app_config/config.json
      - ./chat_histories:/app/chat_histories

  db:
    container_name: engineering-hub-db
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: engineering-hub-redis
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning

  worker:
    container_name: engineering-hub-worker
    build: ./worker
    restart: unless-stopped
    env_file: .env
    environment:
      HTTP_PROXY:  "http://51.158.76.113:9999"
      HTTPS_PROXY: "http://51.158.76.113:9999"
      http_proxy:  "http://51.158.76.113:9999"
      https_proxy: "http://51.158.76.113:9999"
      NO_PROXY:  "localhost,127.0.0.1,nginx,frontend,db,redis,engineering-hub-nginx,engineering-hub-frontend,engineering-hub-db,engineering-hub-redis"
      no_proxy:  "localhost,127.0.0.1,nginx,frontend,db,redis,engineering-hub-nginx,engineering-hub-frontend,engineering-hub-db,engineering-hub-redis"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./worker:/app
      - ./backend/kb_service:/app/kb_service
      - ./config.json:/app_config/config.json
      - ./chat_histories:/app/chat_histories

volumes:
  postgres_data:
    name: engineering-hub_postgres_data
